main: dev.cibmc.spigot.blankplugin.App
name: BlankPlugin
version: 0.1
description: compass track

commands:
  runner:
    usage: /runner [add | remove] [runner]
    description: sets runner to someone
  compass:
    usage: /compass
    description: gives you a tracker compass