main: dev.cibmc.spigot.blankplugin.App
name: CompassTrack
version: 0.1
description: compass that allows you to track other people (WIP)

commands:
  runner:
    usage: /runner [add | remove] [runner]
    description: sets runner to someone
  compass:
    usage: /compass
    description: gives you a tracker compass